### ISSUE TITLE
S2S support

### ISSUE THREAD

**Issue by outlaw-dame** [activitypods/activitypods#246]
Being as that is the more implemented and familiar spec it would be a good idea for ActivityPods to offer support. This would allow a faster adoption of AP, granting users the familiar instance setup but while owning their data as they would have a POD.
Some considerations are intermediary servers. Meaning Alice signs up on an instance memory.social there is logic that upon account creation a POD is created for her in the Memory POD Store. Bob@mastodon.social messages Alice, Mastodon.social HTTP Signature goes to Memory.social and Memory.social needs to forward to Alice's POD, how to make it so the signature doesn't become invalid.

**Comment by srosset81** [comment]
I don't understand the title of your issue, there is already full support for the ActivityPub S2S spec in ActivityPods ?

Regarding intermediary servers, I think this would necessarily require an intermediary actor, with its own keys.

**Comment by Laurin-W** [comment]
Closing as solved.
