### ISSUE TITLE
Use TypeRegistration to store ClassDescription

### ISSUE THREAD

**Issue by srosset81** [activitypods/activitypods#256]
On v2, apps can describe the type of data they handle with a `apods:ClassDescription` resource, which is used to display a nice name of the resources we ask rights to. It is also used in the data browser.

```ttl
<http://localhost:3001/167ed0ba-48db-4695-867d-4627044f98a3>
        a       <http://activitypods.org/ns/core#ClassDescription> ;
        <http://activitypods.org/ns/core#describedBy>
                <http://localhost:3001/app> ;
        <http://activitypods.org/ns/core#describedClass>
                <https://www.w3.org/ns/activitystreams#Event> ;
        <http://activitypods.org/ns/core#labelPredicate>
                <https://www.w3.org/ns/activitystreams#name> ;
        <http://activitypods.org/ns/core#openEndpoint>
                "https://example.app/r" ;
        <http://www.w3.org/2004/02/skos/core#prefLabel>
                "Events" .
```

Now that we have started implementing TypeIndex, which lists TypeRegistrations with class and container path, it seems like a duplicate. We could extend TypeRegistration to include `apods:labelPredicate`, `skos:prefLabel` and `apods:preferredApp`. The `apods:openEndpoint` could be defined in the preferred app.

The ClassDescription could still be used on the app's side.

**Comment by Laurin-W** [comment]
I'm not familiar with TypeIndex so I'm not understanding a lot but it sounds good to converge.
Also, the registering client should have very limited say on explaining to the user what the types are that it is requesting..

**Comment by srosset81** [comment]
Done here #263
