### ISSUE TITLE
Error trying to signup on the website

### ISSUE THREAD

**Issue by grassgoth** [activitypods/activitypods#261]
Attempting to check out this project and I can't signup to try out the software.

Whenever I attempt to register an account on the mypods website linked from the official website, I get the following error:
```
Service 'auth.account.create' is not found
```

**Comment by Laurin-W** [comment]
Heyho, thanks for opening the issue and nice to hear that you are interested in the project :)
Sorry for the late reply, we are on summer break a bit.

Regarding https://mypod.store there was an issue with the server which prevented the backend from restarting correctly. I just fixed it and the server is up again.

If there is anything else, let me know here or open a new issue :)
