### ISSUE TITLE
Tutorial bug: backend yarn install failure 

### ISSUE THREAD

**Issue by MarkCatch** [activitypods/activitypods#346]
Successfully followed tutorial up to here:

![image](https://github.com/user-attachments/assets/738783f0-403c-448d-97d2-2ec5d176830b)
running Ubuntu on WSL on HP laptop:
![image](https://github.com/user-attachments/assets/5508182e-2228-4d9d-8956-94b08cc65588)
Warning with yarn install then command not found:
![image](https://github.com/user-attachments/assets/8acd7ddb-5614-490f-9eef-1106096fc1d7)
red cross after running yarn explain command:
![image](https://github.com/user-attachments/assets/6c422e66-4619-48aa-849d-3bbe5f04b2f3)
Any suggestions?
Kind regards
       Mark

**Comment by Laurin-W** [comment]
Hi @MarkCatch, thanks for raising the issue.

I'm still running yarn version 1.22.22, which works for me. Could you try it with that?

**Comment by MarkCatch** [comment]
OK thanks for the prompt response.
I switched to 1.22.22 as you suggested and made progress. I now have two consoles running frontend and backend

![image](https://github.com/user-attachments/assets/d7f32e0e-bd43-4ea8-95e8-8b6fc300a49f)

But opening the browser doesn't look right?:
![image](https://github.com/user-attachments/assets/ffb26e3f-952f-41bd-9e55-f4b774136b60)

**Comment by Laurin-W** [comment]
Mh, that looks like the activitypods server is down. Did you run `make start` in the root directory?
Remember to run `make stop` again later, as it's consuming quite some RAM :)

**Comment by MarkCatch** [comment]
OK I restarted Pod provider, backend and frontend and hey presto:
![image](https://github.com/user-attachments/assets/3480389c-2c97-4c5c-814e-e8e733fe2f6a)
Thanks for the support

**Comment by MarkCatch** [comment]
Feel free to close

**Comment by srosset81** [comment]
@MarkCatch Great to see it works !
If you run into other issues, feel free to open another issue, or post on our [Matrix space](https://matrix.to/#/#activitypods:matrix.org).
